name: Deploy to DreamHost

on:
  push:
    branches:
      - main # Cambia esto si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DreamHost
        env:
          DREAMHOST_USER: ${{ secrets.DREAMHOST_USER }}
          DREAMHOST_PASS: ${{ secrets.DREAMHOST_PASS }}
          DREAMHOST_HOST: "iad1-shared-b8-23.dreamhost.com"
          DREAMHOST_DOMAIN: "alex.rubikops.com"
        run: |
          echo "Deploying to DreamHost..."
          rsync -avz --delete -e "sshpass -p $DREAMHOST_PASS ssh -o StrictHostKeyChecking=no" ./ $DREAMHOST_USER@$DREAMHOST_HOST:/home/$DREAMHOST_USER/$DREAMHOST_DOMAIN

      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          curl -I --max-time 30 https://alex.rubikops.com | grep "200 OK"

      - name: Notify Success
        if: success()
        run: |
          echo "Deployment successful!" # Aquí podrías integrar con un servicio de notificaciones
