name: Deploy to DreamHost

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DreamHost
        env:
          DREAMHOST_USER: ${{ secrets.DREAMHOST_USER }}
          DREAMHOST_PASS: ${{ secrets.DREAMHOST_PASS }}
          DREAMHOST_HOST: 'iad1-shared-b8-23.dreamhost.com'
          DREAMHOST_DOMAIN: 'alex.rubikops.com'
        run: |
          echo "Deploying to DreamHost..."
          sshpass -p $DREAMHOST_PASS scp -o StrictHostKeyChecking=no -r ./* $DREAMHOST_USER@$DREAMHOST_HOST:/home/$DREAMHOST_USER/$DREAMHOST_DOMAIN
